[package]
name = "example-hardcoded"
version = "0.1.0"
authors = ["Chandler Newman <chandler2newman@hotmail.co.uk>"]
edition = "2018"

[lib]
name = "nss_hardcoded"
crate-type = [ "cdylib" ]

[dependencies]
libc = "0.2"
libnss = { path = "../libnss" }
